# Generated by Django 3.2 on 2021-09-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideteacher',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.personalinfo'),
        ),
        migrations.AddField(
            model_name='classregistration',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classinfo'),
        ),
        migrations.AddField(
            model_name='classregistration',
            name='guide_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.guideteacher'),
        ),
        migrations.AddField(
            model_name='classregistration',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.section'),
        ),
        migrations.AddField(
            model_name='classregistration',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.session'),
        ),
        migrations.AddField(
            model_name='classregistration',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='classregistration',
            unique_together={('class_name', 'section', 'shift', 'guide_teacher')},
        ),
    ]
