# Generated by Django 3.2 on 2021-09-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.enrolledstudent')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
